HS-Continuity/MemberService

- src/main/java/com/yeonieum/memberservice/web/controller/MemberController.java
⚒️구현 기능
- 회원 가입
- 회원 정보 조회
- 회원 정보 수정
- 회원 탈퇴
#️⃣관련 이슈
- KAN 326
- KAN 327
- KAN 328
- KAN 329
- 
📝세부 작업 내용
💬참고 사항
> KAN-325 feat/회원정보 웹레이어 구현

- .gitignore
- src/main/java/com/yeonieum/memberservice/domain/member/dto/MemberRequest.java
- src/main/java/com/yeonieum/memberservice/domain/member/dto/MemberResponse.java
- src/main/java/com/yeonieum/memberservice/domain/member/entity/Member.java
- src/main/java/com/yeonieum/memberservice/domain/member/repository/MemberRepository.java
- src/main/java/com/yeonieum/memberservice/domain/member/service/MemberService.java
⚒️구현 기능
- 회원 가입
- 회원 정보 조회
- 회원 정보 수정
- 회원 탈퇴
#️⃣관련 이슈
- KAN 321
- KAN 322
- KAN 323
- KAN 324
📝세부 작업 내용
💬참고 사항
> KAN-299 feat: 회원서비스 회원정보 관련 기능 추가

- src/main/java/com/yeonieum/memberservice/domain/member/dto/MemberResponse.java
- src/main/java/com/yeonieum/memberservice/domain/member/entity/Member.java
- src/main/java/com/yeonieum/memberservice/domain/member/entity/MemberCoupon.java
- src/main/java/com/yeonieum/memberservice/domain/member/repository/MemberCouponRepository.java
- src/main/java/com/yeonieum/memberservice/domain/member/service/MemberCouponService.java
- src/main/java/com/yeonieum/memberservice/domain/memberstore/dto/MemberStoreResponse.java
- src/main/java/com/yeonieum/memberservice/domain/memberstore/repository/MemberStoreRepository.java
- src/main/java/com/yeonieum/memberservice/domain/memberstore/service/MemberStoreService.java
- src/main/java/com/yeonieum/memberservice/domain/payment/dto/PaymentRequest.java
- src/main/java/com/yeonieum/memberservice/domain/payment/dto/PaymentResponse.java
- src/main/java/com/yeonieum/memberservice/domain/payment/service/PaymentService.java
- src/main/java/com/yeonieum/memberservice/web/controller/MemberCouponController.java
- src/main/java/com/yeonieum/memberservice/web/controller/MemberStoreController.java
- src/main/java/com/yeonieum/memberservice/web/controller/PaymentController.java
- 회원서비스 dto 리팩토링
- Close#368
- 엔티티 → DTO convertedBy 메서드 정의
- DTO → 엔티티 toEntity 메서드 정의
> Refactor/회원서비스 dto 리팩토링

- src/main/java/com/yeonieum/memberservice/domain/address/dto/AddressRequest.java
- src/main/java/com/yeonieum/memberservice/domain/address/dto/AddressResponse.java
- src/main/java/com/yeonieum/memberservice/domain/address/entity/MemberAddress.java
- src/main/java/com/yeonieum/memberservice/domain/address/repository/MemberAddressRepository.java
- src/main/java/com/yeonieum/memberservice/domain/address/service/AddressService.java
⚒️구현 기능
회원주소지 서비스 레이어 구현
#️⃣관련 이슈
KAN-408
KAN-409
KAN-410
KAN-411
KAN-412
📝세부 작업 내용
[x] 회원 주소지 목록 조회
[x] 회원 주소지 등록
[x] 회원 주소지 수정
[x] 회원 주소지 삭제
[x] 회원 주소지 대표 주소지 설정
💬참고 사항
왜 pr template이 안 뜰까요...
> KAN-406 feat: 회원배송지 서비스레이어 구현

- src/main/java/com/yeonieum/memberservice/domain/address/dto/AddressRequest.java
- src/main/java/com/yeonieum/memberservice/domain/address/dto/AddressResponse.java
- src/main/java/com/yeonieum/memberservice/domain/address/entity/MemberAddress.java
- src/main/java/com/yeonieum/memberservice/domain/address/service/AddressService.java
⚒️구현 기능
회원 서비스 필드 추가
#️⃣관련 이슈
KAN-430
KAN-431
KAN-432
📝세부 작업 내용
필드 추가로 인한 회원 배송지 dto, entity, service 수정
💬참고 사항
> KAN-429 refactor: 회원 배송지 필드 수정

- src/main/java/com/yeonieum/memberservice/auth/handler/JwtAuthenticationSuccessHandler.java
- src/main/java/com/yeonieum/memberservice/auth/handler/OAuth2LogoutHandler.java
- src/main/java/com/yeonieum/memberservice/auth/handler/OAuthAuthenticationSuccessHandler.java
- src/main/java/com/yeonieum/memberservice/auth/oauth/CustomOAuth2UserServiceImpl.java
- src/main/java/com/yeonieum/memberservice/auth/provider/JwtAuthenticationProvider.java
- src/main/java/com/yeonieum/memberservice/auth/userdetails/CustomUserDetailsService.java
- src/main/java/com/yeonieum/memberservice/auth/userdetails/CustomUserDto.java
- src/main/java/com/yeonieum/memberservice/auth/util/JwtUtils.java
- src/main/java/com/yeonieum/memberservice/domain/member/entity/Member.java
- src/main/java/com/yeonieum/memberservice/global/converter/RoleConverter.java
- src/main/java/com/yeonieum/memberservice/global/enums/Role.java
[![KAN-471](https://badgen.net/badge/JIRA/KAN-471/blue?icon=jira)](https://jira.company.com/browse/KAN-471) [![PR-21](https://badgen.net/badge/Preview/PR-21/blue)](https://pr-21.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 인증서비스 사용자 롤 구성
- Close{471}
[KAN-471]: https://hysoung-kosa-team4.atlassian.net/browse/KAN-471?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KAN-471  feat: 인증서비스 사용자 롤 구성

- src/main/java/com/yeonieum/memberservice/auth/endpoint/ReIssueAccessTokenApi.java
- src/main/java/com/yeonieum/memberservice/auth/handler/JwtAuthenticationSuccessHandler.java
- src/main/java/com/yeonieum/memberservice/auth/handler/OAuthAuthenticationSuccessHandler.java
- src/main/java/com/yeonieum/memberservice/auth/oauth/CustomOAuth2UserServiceImpl.java
- src/main/java/com/yeonieum/memberservice/auth/util/JwtUtils.java
[![KAN-472](https://badgen.net/badge/JIRA/KAN-472/blue?icon=jira)](https://jira.company.com/browse/KAN-472) [![PR-22](https://badgen.net/badge/Preview/PR-22/blue)](https://pr-22.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
-  리프레시토큰 구현
- Closa{472}
[KAN-472]: https://hysoung-kosa-team4.atlassian.net/browse/KAN-472?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KAN-472  feat: 인증서비스 리프레시토큰 구현

- src/main/java/com/yeonieum/memberservice/domain/address/dto/AddressRequest.java
- src/main/java/com/yeonieum/memberservice/domain/address/dto/AddressResponse.java
- src/main/java/com/yeonieum/memberservice/domain/address/repository/MemberAddressRepository.java
- src/main/java/com/yeonieum/memberservice/domain/address/service/AddressService.java
- src/main/java/com/yeonieum/memberservice/web/controller/MemberAddressController.java
[![KAN-325](https://badgen.net/badge/JIRA/KAN-325/blue?icon=jira)](https://jira.company.com/browse/KAN-325) [![PR-23](https://badgen.net/badge/Preview/PR-23/blue)](https://pr-23.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 회원 배송지 CRUD controller 구현
- KAN-413
- KAN-414
- KAN-415
- KAN-416
- KAN-417
- 리뷰어에게 참고할만한 사항을 입력해주세요.
[KAN-325]: https://hysoung-kosa-team4.atlassian.net/browse/KAN-325?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Kan-325 feat: 회원정보 웹레이어 구현

- build.gradle
- src/main/java/com/yeonieum/memberservice/auth/endpoint/LogoutApi.java
- src/main/java/com/yeonieum/memberservice/auth/endpoint/ReIssueAccessTokenApi.java
- src/main/java/com/yeonieum/memberservice/auth/service/TokenService.java
- src/main/java/com/yeonieum/memberservice/auth/util/JwtUtils.java
- src/main/java/com/yeonieum/memberservice/global/config/RedisConfig.java
- src/main/java/com/yeonieum/memberservice/global/config/SecurityConfig.java
[![KAN-473](https://badgen.net/badge/JIRA/KAN-473/blue?icon=jira)](https://jira.company.com/browse/KAN-473) [![PR-24](https://badgen.net/badge/Preview/PR-24/blue)](https://pr-24.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 인증서비스 토큰 영속화 및 로그아웃
- Close{473}
- 액세스토큰은 로그아웃 시 블랙리스트 처리하였습니다. TTL은 액세스토큰 만료까지 남은 시간으로 설정
- 리프레시토큰은 로그인 시 username을 키로 가지는 value로 저장하였고, 로그아웃 시 삭제 처리 하였습니다.
[KAN-473]: https://hysoung-kosa-team4.atlassian.net/browse/KAN-473?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KAN-473  feat: 인증서비스 토큰 영속화 및 로그아웃

- build.gradle
- src/main/java/com/yeonieum/memberservice/domain/sms/dto/SmsRequest.java
- src/main/java/com/yeonieum/memberservice/domain/sms/service/SmsVarificationService.java
- src/main/java/com/yeonieum/memberservice/global/config/RedisConfig.java
- src/main/java/com/yeonieum/memberservice/web/controller/SmsVerificationController.java
[![KAN-476](https://badgen.net/badge/JIRA/KAN-476/blue?icon=jira)](https://jira.company.com/browse/KAN-476) [![PR-26](https://badgen.net/badge/Preview/PR-26/blue)](https://pr-26.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 인증서비스 문자인증 구현
- Closa{476}
[KAN-476]: https://hysoung-kosa-team4.atlassian.net/browse/KAN-476?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KAN-476  feat: 인증서비스 문자인증 구현

- src/main/java/com/yeonieum/memberservice/domain/address/service/AddressService.java
- src/main/java/com/yeonieum/memberservice/web/controller/MemberAddressController.java
[![KAN-495](https://badgen.net/badge/JIRA/KAN-495/blue?icon=jira)](https://jira.company.com/browse/KAN-495) [![PR-28](https://badgen.net/badge/Preview/PR-28/blue)](https://pr-28.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 특정 memberAddressId로 배송지 조회 기능 추가
- KAN-506
[KAN-495]: https://hysoung-kosa-team4.atlassian.net/browse/KAN-495?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Kan-495  refactor: 회원서비스 회원배송지 웹레이어 수정

- src/main/java/com/yeonieum/memberservice/domain/payment/dto/PaymentResponse.java
[![KAN-508](https://badgen.net/badge/JIRA/KAN-508/blue?icon=jira)](https://jira.company.com/browse/KAN-508) [![PR-29](https://badgen.net/badge/Preview/PR-29/blue)](https://pr-29.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 결제카드 조회시 만료일 추가
- KAN-508
> KAN-508 feat: 결제카드 조회시 만료일 추가

- build.gradle
- src/main/java/com/yeonieum/memberservice/domain/member/entity/MemberCoupon.java
- src/main/java/com/yeonieum/memberservice/domain/member/service/MemberCouponService.java
- src/main/java/com/yeonieum/memberservice/web/controller/MemberCouponController.java
[![KAN-510](https://badgen.net/badge/JIRA/KAN-510/blue?icon=jira)](https://jira.company.com/browse/KAN-510) [![PR-30](https://badgen.net/badge/Preview/PR-30/blue)](https://pr-30.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 회원쿠폰상태변경 API구현
- Close{510}
[KAN-510]: https://hysoung-kosa-team4.atlassian.net/browse/KAN-510?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KAN-510 feat: 회원쿠폰상태변경 API구현

- src/main/java/com/yeonieum/memberservice/domain/address/dto/AddressResponse.java
[![KAN-495](https://badgen.net/badge/JIRA/KAN-495/blue?icon=jira)](https://jira.company.com/browse/KAN-495) [![PR-31](https://badgen.net/badge/Preview/PR-31/blue)](https://pr-31.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 오타 수정
- KAN-519
- 리뷰어에게 참고할만한 사항을 입력해주세요.
[KAN-495]: https://hysoung-kosa-team4.atlassian.net/browse/KAN-495?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KAN-495  refactor:회원서비스 회원배송지 오타 수정

- src/main/java/com/yeonieum/memberservice/auth/endpoint/LogoutApi.java
- src/main/java/com/yeonieum/memberservice/domain/member/dto/MemberResponse.java
- src/main/java/com/yeonieum/memberservice/domain/member/service/MemberService.java
- src/main/java/com/yeonieum/memberservice/global/config/SecurityConfig.java
- src/main/java/com/yeonieum/memberservice/web/controller/MemberController.java
- src/main/java/com/yeonieum/memberservice/web/controller/SmsVerificationController.java
[![KAN-579](https://badgen.net/badge/JIRA/KAN-579/blue?icon=jira)](https://jira.company.com/browse/KAN-579) [![PR-32](https://badgen.net/badge/Preview/PR-32/blue)](https://pr-32.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 회원 요약정보조회api 구현
- Close{579}
[KAN-579]: https://hysoung-kosa-team4.atlassian.net/browse/KAN-579?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KAN-579  feat: 회원 요약정보조회api 구현

- src/main/java/com/yeonieum/memberservice/auth/endpoint/LogoutApi.java
- src/main/java/com/yeonieum/memberservice/domain/member/dto/MemberRequest.java
- src/main/java/com/yeonieum/memberservice/domain/member/service/MemberService.java
- src/main/java/com/yeonieum/memberservice/global/config/SecurityConfig.java
[![KAN-594](https://badgen.net/badge/JIRA/KAN-594/blue?icon=jira)](https://jira.company.com/browse/KAN-594) [![PR-34](https://badgen.net/badge/Preview/PR-34/blue)](https://pr-34.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 모바일 회원 비밀번호 검증 / 변경
- KAN-594
- KAN-272(security 관련)
- KAN-271(logout 관련)
- 이제 프론트 분들은 Security 계속 수정 안하셔도 됩니다.
[KAN-594]: https://hysoung-kosa-team4.atlassian.net/browse/KAN-594?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KAN-594 refactor: 회원 서비스 비밀번호 변경 검증

- src/main/java/com/yeonieum/memberservice/domain/address/exception/AddressException.java
- src/main/java/com/yeonieum/memberservice/domain/address/exception/AddressExceptionCode.java
- src/main/java/com/yeonieum/memberservice/domain/address/service/AddressService.java
- src/main/java/com/yeonieum/memberservice/global/exceptions/code/CustomExceptionCode.java
- src/main/java/com/yeonieum/memberservice/global/exceptions/exception/CustomException.java
- src/main/java/com/yeonieum/memberservice/global/exceptions/handler/GlobalExceptionHandler.java
- src/main/java/com/yeonieum/memberservice/global/responses/ErrorResponse.java
[![KAN-604](https://badgen.net/badge/JIRA/KAN-604/blue?icon=jira)](https://jira.company.com/browse/KAN-604) [![PR-36](https://badgen.net/badge/Preview/PR-36/blue)](https://pr-36.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 배송지 예외처리 정의
- KAN-604
[KAN-604]: https://hysoung-kosa-team4.atlassian.net/browse/KAN-604?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KAN-604 feat: 배송지 예외처리 정의

- src/main/java/com/yeonieum/memberservice/domain/address/service/AddressService.java
- src/main/java/com/yeonieum/memberservice/domain/member/exception/MemberException.java
- src/main/java/com/yeonieum/memberservice/domain/member/exception/MemberExceptionCode.java
- src/main/java/com/yeonieum/memberservice/domain/member/service/MemberCouponService.java
- src/main/java/com/yeonieum/memberservice/domain/member/service/MemberService.java
[![KAN-606](https://badgen.net/badge/JIRA/KAN-606/blue?icon=jira)](https://jira.company.com/browse/KAN-606) [![PR-37](https://badgen.net/badge/Preview/PR-37/blue)](https://pr-37.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 회원 예외처리 정의
- KAN-606
[KAN-606]: https://hysoung-kosa-team4.atlassian.net/browse/KAN-606?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KAN-606 feat: 회원 예외처리 정의

- src/main/java/com/yeonieum/memberservice/auth/endpoint/ReIssueAccessTokenApi.java
- src/main/java/com/yeonieum/memberservice/auth/util/JwtUtils.java
[![KAN-608](https://badgen.net/badge/JIRA/KAN-608/blue?icon=jira)](https://jira.company.com/browse/KAN-608) [![PR-39](https://badgen.net/badge/Preview/PR-39/blue)](https://pr-39.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 액세스토큰 재발급 로직 수정
- Close{608}
[KAN-608]: https://hysoung-kosa-team4.atlassian.net/browse/KAN-608?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KAN-608 feat: 액세스토큰 재발급 로직 수정

- build.gradle
- src/main/java/com/yeonieum/memberservice/domain/member/dto/MemberRequest.java
- src/main/java/com/yeonieum/memberservice/domain/member/service/MemberService.java
- src/main/java/com/yeonieum/memberservice/global/exceptions/handler/GlobalExceptionHandler.java
- src/main/java/com/yeonieum/memberservice/global/responses/ErrorResponse.java
- src/main/java/com/yeonieum/memberservice/web/controller/MemberController.java
[![KAN-617](https://badgen.net/badge/JIRA/KAN-617/blue?icon=jira)](https://jira.company.com/browse/KAN-617) [![PR-40](https://badgen.net/badge/Preview/PR-40/blue)](https://pr-40.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 회원 Validation 정의
- KAN-617
[KAN-617]: https://hysoung-kosa-team4.atlassian.net/browse/KAN-617?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KAN-617 feat: 회원 Validation 정의

- src/main/java/com/yeonieum/memberservice/domain/address/dto/AddressRequest.java
- src/main/java/com/yeonieum/memberservice/web/controller/MemberAddressController.java
[![KAN-619](https://badgen.net/badge/JIRA/KAN-619/blue?icon=jira)](https://jira.company.com/browse/KAN-619) [![PR-41](https://badgen.net/badge/Preview/PR-41/blue)](https://pr-41.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 배송지 Validation 정의
- KAN-619
[KAN-619]: https://hysoung-kosa-team4.atlassian.net/browse/KAN-619?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KAN-619 feat: 배송지 Validation 정의

- src/main/java/com/yeonieum/memberservice/domain/memberstore/repository/MemberStoreRepositoryImpl.java
[![KAN-628](https://badgen.net/badge/JIRA/KAN-628/blue?icon=jira)](https://jira.company.com/browse/KAN-628) [![PR-43](https://badgen.net/badge/Preview/PR-43/blue)](https://pr-43.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 회원업체조회 like 연산 적용
- KAN-628
[KAN-628]: https://hysoung-kosa-team4.atlassian.net/browse/KAN-628?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KAN-628 feat: 회원업체조회 like 연산 적용

- src/main/java/com/yeonieum/memberservice/auth/handler/JwtAuthenticationSuccessHandler.java
- src/main/java/com/yeonieum/memberservice/global/config/RedisConfig.java
[![KAN-629](https://badgen.net/badge/JIRA/KAN-629/blue?icon=jira)](https://jira.company.com/browse/KAN-629) [![PR-44](https://badgen.net/badge/Preview/PR-44/blue)](https://pr-44.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 레디스 구성정보 수정
- #{629}
[KAN-629]: https://hysoung-kosa-team4.atlassian.net/browse/KAN-629?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KAN-629 fix: 레디스 구성정보 수정

- src/main/java/com/yeonieum/memberservice/auth/handler/JwtAuthenticationSuccessHandler.java
[![KAN-633](https://badgen.net/badge/JIRA/KAN-633/blue?icon=jira)](https://jira.company.com/browse/KAN-633) [![PR-45](https://badgen.net/badge/Preview/PR-45/blue)](https://pr-45.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 일반로그인 수정
- #{633}
[KAN-633]: https://hysoung-kosa-team4.atlassian.net/browse/KAN-633?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KAN-633 fix: 일반로그인 수정

- build.gradle
- src/main/java/com/yeonieum/memberservice/domain/member/entity/MemberStoreId.java
- src/main/java/com/yeonieum/memberservice/domain/memberstore/repository/MemberStoreRepository.java
- src/main/java/com/yeonieum/memberservice/domain/memberstore/service/MemberStoreService.java
- src/main/java/com/yeonieum/memberservice/infrastructure/dto/OrderEventMessage.java
- src/main/java/com/yeonieum/memberservice/infrastructure/dto/RegularDeliveryEventMessage.java
- src/main/java/com/yeonieum/memberservice/infrastructure/messaging/OrderEventConsumer.java
[![KAN-636](https://badgen.net/badge/JIRA/KAN-636/blue?icon=jira)](https://jira.company.com/browse/KAN-636) [![PR-46](https://badgen.net/badge/Preview/PR-46/blue)](https://pr-46.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 최초주문시 자동회원가입
- #{636}
[KAN-636]: https://hysoung-kosa-team4.atlassian.net/browse/KAN-636?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KAN-636  feat: 최초주문시 자동회원가입

- src/main/java/com/yeonieum/memberservice/domain/member/service/MemberService.java
- src/main/java/com/yeonieum/memberservice/domain/memberstore/repository/MemberStoreRepositoryCustom.java
- src/main/java/com/yeonieum/memberservice/domain/memberstore/repository/MemberStoreRepositoryImpl.java
- src/main/java/com/yeonieum/memberservice/web/controller/MemberController.java
[![KAN-638](https://badgen.net/badge/JIRA/KAN-638/blue?icon=jira)](https://jira.company.com/browse/KAN-638) [![PR-47](https://badgen.net/badge/Preview/PR-47/blue)](https://pr-47.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 회원정보 필터링 메서드 구현
- KAN-638
- QueryDSL을 사용하여 회원이름과 회원전화번호를 필터링 메서드 구현
- 필터링 된 정보와 그들의 회원 ID 반환
[KAN-638]: https://hysoung-kosa-team4.atlassian.net/browse/KAN-638?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KAN-638 feat: 회원정보 필터링 메서드 구현

- src/main/java/com/yeonieum/memberservice/domain/member/dto/MemberResponse.java
- src/main/java/com/yeonieum/memberservice/domain/member/repository/MemberRepository.java
- src/main/java/com/yeonieum/memberservice/domain/member/service/MemberService.java
- src/main/java/com/yeonieum/memberservice/web/controller/MemberController.java
[![KAN-630](https://badgen.net/badge/JIRA/KAN-630/blue?icon=jira)](https://jira.company.com/browse/KAN-630) [![PR-49](https://badgen.net/badge/Preview/PR-49/blue)](https://pr-49.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 정기주문조회 시 사용되는 회원정보벌크조회 API구현
- #{630}
[KAN-630]: https://hysoung-kosa-team4.atlassian.net/browse/KAN-630?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KAN-630 feat: 정기주문조회 시 사용되는 회원정보벌크조회 API구현

- src/main/java/com/yeonieum/memberservice/domain/member/dto/MemberResponse.java
- src/main/java/com/yeonieum/memberservice/domain/member/service/MemberService.java
- src/main/java/com/yeonieum/memberservice/domain/memberstore/repository/MemberStoreRepositoryCustom.java
- src/main/java/com/yeonieum/memberservice/domain/memberstore/repository/MemberStoreRepositoryImpl.java
- src/main/java/com/yeonieum/memberservice/web/controller/MemberController.java
[![KAN-644](https://badgen.net/badge/JIRA/KAN-644/blue?icon=jira)](https://jira.company.com/browse/KAN-644) [![PR-50](https://badgen.net/badge/Preview/PR-50/blue)](https://pr-50.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 주문조회시 필요한 회원정보 메서드 간소화
- KAN-644
[KAN-644]: https://hysoung-kosa-team4.atlassian.net/browse/KAN-644?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KAN-644 feat: 주문조회시 필요한 회원정보 메서드 간소화

- .github/workflows/member-aws.yml
- Dockerfile
- src/main/java/com/yeonieum/memberservice/domain/memberstore/repository/MemberStoreRepositoryImpl.java
- t4-memberservice-task-definition-revision1.json
[![KAN-671](https://badgen.net/badge/JIRA/KAN-671/blue?icon=jira)](https://jira.company.com/browse/KAN-671) [![PR-51](https://badgen.net/badge/Preview/PR-51/blue)](https://pr-51.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 회원서비스 배포자동화 스크립트 작성
- KAN-671
- 리뷰어에게 참고할만한 사항을 입력해주세요.
[KAN-671]: https://hysoung-kosa-team4.atlassian.net/browse/KAN-671?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KAN-671  feat: 회원서비스 배포자동화 스크립트 작성

- src/main/java/com/yeonieum/memberservice/domain/member/dto/MemberResponse.java
- src/main/java/com/yeonieum/memberservice/domain/member/entity/Member.java
- src/main/java/com/yeonieum/memberservice/domain/member/service/MemberService.java
- src/main/java/com/yeonieum/memberservice/global/auditing/BaseEntity.java
- src/main/java/com/yeonieum/memberservice/web/controller/MemberController.java
[![KAN-684](https://badgen.net/badge/JIRA/KAN-684/blue?icon=jira)](https://jira.company.com/browse/KAN-684) [![PR-52](https://badgen.net/badge/Preview/PR-52/blue)](https://pr-52.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 회원엔티티 auditing 적용
- KAN-684
[KAN-684]: https://hysoung-kosa-team4.atlassian.net/browse/KAN-684?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KAN-684 feat: 회원엔티티 auditing 적용

- src/main/java/com/yeonieum/memberservice/auth/util/JwtUtils.java
- src/main/java/com/yeonieum/memberservice/domain/address/service/AddressService.java
- src/main/java/com/yeonieum/memberservice/web/controller/MemberAddressController.java
[![KAN-583](https://badgen.net/badge/JIRA/KAN-583/blue?icon=jira)](https://jira.company.com/browse/KAN-583) [![PR-55](https://badgen.net/badge/Preview/PR-55/blue)](https://pr-55.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 오타 및 버그수정
- Close{583}
- 리뷰어에게 참고할만한 사항을 입력해주세요.
[KAN-583]: https://hysoung-kosa-team4.atlassian.net/browse/KAN-583?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KAN-583 hotfix: 버그수정

- src/main/java/com/yeonieum/memberservice/auth/filter/JwtAuthorizationFilter.java
- src/main/java/com/yeonieum/memberservice/global/config/SecurityConfig.java
[![KAN-583](https://badgen.net/badge/JIRA/KAN-583/blue?icon=jira)](https://jira.company.com/browse/KAN-583) [![PR-56](https://badgen.net/badge/Preview/PR-56/blue)](https://pr-56.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 구현 기능을 적어주세요.
- Close{583}
[KAN-583]: https://hysoung-kosa-team4.atlassian.net/browse/KAN-583?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KAN-583  hotfix: jwt인가필터 추가

- src/main/java/com/yeonieum/memberservice/auth/endpoint/LogoutApi.java
- src/main/java/com/yeonieum/memberservice/auth/filter/JwtAuthorizationFilter.java
- src/main/java/com/yeonieum/memberservice/auth/util/JwtUtils.java
- src/main/java/com/yeonieum/memberservice/global/config/SecurityConfig.java
[![KAN-583](https://badgen.net/badge/JIRA/KAN-583/blue?icon=jira)](https://jira.company.com/browse/KAN-583) [![PR-57](https://badgen.net/badge/Preview/PR-57/blue)](https://pr-57.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- CORS 도메인 프로퍼티 주입 및 인가필터 수정
- Closa{583}
[KAN-583]: https://hysoung-kosa-team4.atlassian.net/browse/KAN-583?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KAN-583 fix: CORS 도메인 프로퍼티 주입 및 인가필터 수정

- src/main/java/com/yeonieum/memberservice/domain/member/service/MemberService.java
- src/main/java/com/yeonieum/memberservice/web/controller/MemberController.java
- src/main/java/com/yeonieum/memberservice/web/controller/SmsVerificationController.java
[![KAN-695](https://badgen.net/badge/JIRA/KAN-695/blue?icon=jira)](https://jira.company.com/browse/KAN-695) [![PR-53](https://badgen.net/badge/Preview/PR-53/blue)](https://pr-53.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 회원가입 중복 검사
- KAN-695
[KAN-695]: https://hysoung-kosa-team4.atlassian.net/browse/KAN-695?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KAN-695 feat: 회원가입 아이디 전화번호 중복 검사

- build.gradle
- src/main/java/com/yeonieum/memberservice/MemberserviceApplication.java
- src/main/java/com/yeonieum/memberservice/global/auth/Role.java
- src/main/java/com/yeonieum/memberservice/global/auth/RoleMetaData.java
- src/main/java/com/yeonieum/memberservice/global/auth/RoleMetaDataCollector.java
- src/main/java/com/yeonieum/memberservice/global/config/FeignConfig.java
- src/main/java/com/yeonieum/memberservice/infrastructure/CustomerFeignClient.java
- src/main/java/com/yeonieum/memberservice/web/controller/MemberAddressController.java
- src/main/java/com/yeonieum/memberservice/web/controller/MemberController.java
- src/main/java/com/yeonieum/memberservice/web/controller/MemberCouponController.java
- src/main/java/com/yeonieum/memberservice/web/controller/MemberStoreController.java
- src/main/java/com/yeonieum/memberservice/web/controller/PaymentController.java
- src/main/java/com/yeonieum/memberservice/web/controller/PermissionController.java
- src/main/java/com/yeonieum/memberservice/web/controller/SmsVerificationController.java
- src/main/resources/bootstrap.yml
[![KAN-701](https://badgen.net/badge/JIRA/KAN-701/blue?icon=jira)](https://jira.company.com/browse/KAN-701) [![PR-61](https://badgen.net/badge/Preview/PR-61/blue)](https://pr-61.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
-  롤메타데이터수집기 구현
-#{701}
[KAN-701]: https://hysoung-kosa-team4.atlassian.net/browse/KAN-701?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KAN-701  feat: 롤메타데이터수집기 구현

- src/main/java/com/yeonieum/memberservice/global/auth/RoleMetaDataCollector.java
[![KAN-701](https://badgen.net/badge/JIRA/KAN-701/blue?icon=jira)](https://jira.company.com/browse/KAN-701) [![PR-63](https://badgen.net/badge/Preview/PR-63/blue)](https://pr-63.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 롤메타데이터 수집기 수정
- #{701}
[KAN-701]: https://hysoung-kosa-team4.atlassian.net/browse/KAN-701?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KAN-701 hotfix : 롤메타데이터 수집기 수정
